language: node_js
node_js:
  - "8.0.0"
before_install:
  - "npm install stylelint -g"
install:
  - "yarn"
script:
  - "yarn run lint"
  - "yarn run build"
cache:
  yarn: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: "public/"
  email: "jekripreclaroorlina@gmail.com"
